use students;
select * from student;
create table more (id INT primary key,ad_date datetime, address varchar(100) not null, marks integer not null);
select * from more;
insert into more values ( 100 , "2001-10-23" ,"korba",95);
insert into more values(101, "2002-10-23","champa",94);
insert into more values(102,"2003-10-23","bilaspur",96);
insert into more values(103,"2004-10-23","bhatapara",95);
insert into more values (110,"2005-10-23","raipur",90);
select * from student as s inner join more as m on s.id = m.id;
select * from student as s left join more as m on s.id = m.id;
select * from student as s right join more as m on s.id=m.id;
select * from student as s left join more as m on s.id = m.id union select * from student as s right join more as m on s.id=m.id;
create table employee(empid INT primary key,empname varchar(50),managerid INT unique key);
insert into employee values(1,"agni",3);
insert into employee values(2,"akash",4);
insert into employee values(3,"dharti",2);
insert into employee values(4,"vayu",1);
select * from employee;
select t1.empname as managername,t2.empname as employeename from employee as t1 join employee as t2 on t1.empid = t2.managerid;
alter table more add column name varchar(50);
update more set name = "sanu" where id = 100;
update more set name = "arjun " where id  = 101;
update more set name = "kavya" where id = 102;
update more set name = "Swati" where id = 103;
update more set name = "annu" where id = 110;
select id,name from student union select id,name from more;
select id,name from student union all select id,name from more;
